### ISSUE TITLE
How to compute values_networks and values_planar?

### ISSUE THREAD

**Issue by NVessel** [andreabedini/planar-graph-sampler#1]
Hello! I can't understand how you got these values in values_networks and values_planar files. I suppose it's all coefficients for generating functions but I still don't get it. Could you help?

**Comment by andreabedini** [comment]
Thats' a good question @NVessel! The very brief answer is that you need to solve a big system of equations. I suggest you start by reading Eric's [paper](http://www.lix.polytechnique.fr/~fusy/Articles/Fusy08_planar_graphs.pdf) if you haven't already.

Those files were computed by the Maple notebooks in the repo. I managed to use the free [Maple Player](https://www.maplesoft.com/products/maple/Mapleplayer/) to convert the notebook (the one I think I had used, I don't remember why there's two) to pdf.

See https://github.com/andreabedini/planar-graph-sampler/blob/master/EvalutationNew.pdf

**Comment by NVessel** [comment]
Thanks! I've already read this article but I haven't found system of equations. Can you point that out for me in article please?

**Comment by andreabedini** [comment]
It's complicated. Eric's paper delves into the details of how to decompose the generating function for planar graphs in a way that allows us to get a [Boltzmann sampler](https://en.wikipedia.org/wiki/Boltzmann_sampler) out of it (if my memory doesn't fail me, it's been 10 years). What Eric call "decomposition grammar" are basically the equations between generating functions that we need to solve. E.g. the `system_networks` set of equations in my notebook is the translation of the decomposition `(N)` at page 24 of the paper.

**Comment by NVessel** [comment]
Thank you very much! I'll check it

**Comment by NVessel** [comment]
Could you please tell me why you do use D letter in derived functions in your notebook? I'm not so strong in calculus

**Comment by andreabedini** [comment]
`D` in the notebook is the generating function of bicolored binary trees, as described in the first paragraph. If you tell me more about your project I might be able to assist you better (I might).

edit: for added context, I think at the time it took me 3 months of work to understand the algorithm and the computation involved :)

**Comment by NVessel** [comment]
Thanks for assist. Well, what I'm about to do is to generate random 3-connected graphs, should be edge-rooted I guess. Yeah, that's the purpose.I think exact size sampler would be sufficient. What do you think about it?

**Comment by andreabedini** [comment]
Yes, it should work. If we were to believe the notebook then you should be able to obtain graphs of size 10000.

**Comment by NVessel** [comment]
Thanks!

**Comment by NVessel** [comment]
@andreabedini Could you please tell me what DemiArete class stands for? I didn't quite understand what data structure that should reflect.

**Comment by andreabedini** [comment]
Eric is French and "demi arete" stands for "half edge".  It's basically a graph with severed edges, yet to be connected to each other.

**Comment by NVessel** [comment]
Well, thanks.

**Comment by NVessel** [comment]
@andreabedini I've got another question, please answer. So I've got values_networks and values_planar not for 5-vertex graphs I guess, but I launched it to generate 5-vertex and work was okay. I remember that we have to recalculate evaluations every time for new vertex size, but I don't really know why. It might be connected with time of generating I suppose.

**Comment by andreabedini** [comment]
With a Boltzman sampler the size of the generated object is a random variable. Adjusting the parameters of the sampler (the "recalculation" you mention) you can adjust the probability that the size is within a range of your choice. These two papers might help with the general ideas behind Boltzman samplers:
* http://algo.inria.fr/flajolet/Publications/DuFlLoSc04.pdf
* https://web.eecs.umich.edu/~pettie/theoryseminar/papers/Flajolet-etal-Boltzmann.pdf

**Comment by NVessel** [comment]
Thanks! I think I got it.

**Comment by NVessel** [comment]
By the way, could you tell why we need driver.py?

**Comment by andreabedini** [comment]
I think I wrote `driver.py` to automate running the generator until I get the right number of samples of the correct size.

**Comment by NVessel** [comment]
Understood, thanks

**Comment by NVessel** [comment]
@andreabedini if you can recall, can you please tell how printForBedini works. I mean, yeah, it's used for printing via traversal, but the question is: when we use it to print graph, does it include root edge or not?

**Comment by andreabedini** [comment]
I made `printForBedini` because I needed a slightly different output format. When outputing a planar graph, all edges and nodes should be included AFAIR.

**Comment by NVessel** [comment]
Thanks

**Comment by NVessel** [comment]
Thank you very much for all your help! I finally did it.
